load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")


nodejs_binary(
    name = "bin",
    data = [
    ],
    entry_point = ":main.js",
)

